/** Short SPC term definitions (≤ 30 words) in Spanish for non-experts. */
export const SPC_GLOSSARY: Record<string, string> = {
  UCL: 'Límite de Control Superior: frontera estadística a +3σ. Un punto sobre este límite indica una causa asignable que requiere investigación inmediata.',
  LCL: 'Límite de Control Inferior: frontera estadística a -3σ. Un punto bajo este límite indica una causa asignable que requiere investigación inmediata.',
  CL: 'Línea Central: media del proceso (X̄̄). Representa el comportamiento promedio esperado bajo condiciones normales de operación.',
  Cp: 'Capacidad potencial a corto plazo: mide si la variación del proceso cabe dentro de los límites de especificación. Cp ≥ 1.33 es adecuado.',
  Cpk: 'Capacidad real a corto plazo: como Cp pero penaliza el proceso si no está centrado. Cpk < 1.0 significa que el proceso produce defectos.',
  Pp: 'Desempeño potencial a largo plazo: igual que Cp pero usando la variación total observada (σ global), no la variación interna de subgrupos.',
  Ppk: 'Desempeño real a largo plazo: como Cpk usando σ global. Incluye variaciones por turno, operador, lote u otras fuentes de largo plazo.',
  'Nelson 1': 'Un punto fuera de los límites de control (±3σ). Señal fuerte de causa asignable: parar y buscar la causa inmediatamente.',
  'Nelson 2': '9 puntos consecutivos en el mismo lado de la línea central. Indica un desplazamiento sostenido en la media del proceso.',
  'Nelson 3': '6 puntos consecutivos en tendencia estrictamente creciente o decreciente. Indica deriva sistemática: desgaste, temperatura u otro factor.',
  'Nelson 4': '14 puntos alternando arriba-abajo consecutivamente. Puede indicar mezcla de dos fuentes de variación (dos turnos, dos materiales).',
  'Nelson 5': '2 de 3 puntos consecutivos más allá de ±2σ en el mismo lado. Señal de desplazamiento moderado de la media del proceso.',
  'Nelson 6': '4 de 5 puntos consecutivos más allá de ±1σ en el mismo lado. Indica un desplazamiento menor pero sostenido del proceso.',
  'Nelson 7': '15 puntos consecutivos dentro de ±1σ. El proceso es demasiado uniforme; puede indicar estratificación o límites de control incorrectos.',
  'Nelson 8': '8 puntos consecutivos más allá de ±1σ a ambos lados de la línea central. Sugiere distribución bimodal o mezcla de dos procesos distintos.',
  'X̄-R': 'Carta de Medias y Rangos. Usada con subgrupos de n ≤ 10. La carta X̄ monitorea la media del proceso; la carta R monitorea la variación interna.',
  'X̄-S': 'Carta de Medias y Desviaciones Típicas. Usada con subgrupos de n > 10. Más potente que X̄-R para detectar cambios de variación con muestras grandes.',
  'I-MR': 'Carta de Individuales y Rangos Móviles. Usada cuando solo se dispone de una medición por período (n=1). Muy sensible a la no-normalidad.',
  sigma: 'σ (sigma): desviación estándar, medida de la variabilidad del proceso. En SPC se estima desde R̄ (dentro del subgrupo) para aislar la causa común.',
  subgrupo: 'Conjunto pequeño de mediciones tomadas bajo condiciones esencialmente iguales. La variación dentro del subgrupo estima la variación de causa común.',
  'causa asignable': 'Fuente de variación especial, identificable y eliminable (avería, cambio de lote, error de operador). Produce puntos fuera de control.',
  'causa común': 'Variación aleatoria inherente al proceso cuando está bajo control estadístico. Solo se reduce cambiando el sistema (no acciones puntuales).',
};
